"use client";

import { useEffect, useMemo, useState, type ComponentType } from "react";
import {
  AlertTriangle, Archive, Check, CheckCircle2, ChevronDown, ChevronRight,
  Code2, Command, Database, Disc3, Download, FileCode2, FilePlus2, FlaskConical,
  Gauge, HardDrive, Info, Languages, Layers3, LayoutDashboard, Library, LockKeyhole, Menu,
  Moon, MoreHorizontal, Package, Play, Plus, RefreshCcw, Search, Settings, ShieldAlert, ShieldCheck,
  Sparkles, Sun, TerminalSquare, Usb, Users, Wrench, X, XCircle, Zap,
} from "lucide-react";
import { adapters } from "@/src/core/adapters";
import { evaluateUsbTarget } from "@/src/core/usb-safety";
import { canStartBuild, validateBuild } from "@/src/core/validation";
import type { InstallProfile, IsoImage, JobLog, OsFamily, ValidationIssue } from "@/src/core/types";
import { exampleDevices, exampleImages, exampleJobs, exampleProfiles } from "@/src/data/examples";

type Page = "dashboard" | "isos" | "profiles" | "multiboot" | "builder" | "drivers" | "scripts" | "tests" | "logs" | "settings";
type NavItem = { id: Page; label: string; icon: ComponentType<{ size?: number; strokeWidth?: number }> };
const nav: NavItem[] = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { id: "isos", label: "ISO-Bibliothek", icon: Disc3 },
  { id: "profiles", label: "Installationsprofile", icon: Layers3 }, { id: "multiboot", label: "Multi-Boot-Sticks", icon: Usb },
  { id: "builder", label: "ISO-Builder", icon: Wrench }, { id: "drivers", label: "Treiber & Pakete", icon: Package },
  { id: "scripts", label: "Skripte", icon: FileCode2 }, { id: "tests", label: "Virtuelle Tests", icon: FlaskConical },
  { id: "logs", label: "Logs", icon: TerminalSquare }, { id: "settings", label: "Einstellungen", icon: Settings },
];
const profileSections: Array<[string, string, ComponentType<{ size?: number }>]> = [
  ["basic", "Grundkonfiguration", Gauge], ["users", "Benutzerkonten", Users], ["storage", "Festplatte", HardDrive],
  ["network", "Netzwerk", Zap], ["software", "Software", Package], ["compat", "Kompatibilität", ShieldAlert], ["files", "Erzeugte Dateien", Code2],
];
const settingsSections: Array<[string, string, ComponentType<{ size?: number }>]> = [
  ["general", "Allgemein", Settings], ["security", "Sicherheit", ShieldCheck], ["tools", "Externe Werkzeuge", Wrench],
  ["rules", "Kompatibilitätsregeln", Database], ["language", "Sprache & Barrierefreiheit", Languages],
];

const pageTitles: Record<Page, [string, string]> = {
  dashboard: ["Guten Morgen", "Alles Wichtige für deine Installationsmedien auf einen Blick."],
  isos: ["ISO-Bibliothek", "Images analysieren, prüfen und Installationsprofilen zuweisen."],
  profiles: ["Installationsprofile", "Wiederverwendbare Konfigurationen für Windows und Linux."],
  multiboot: ["Multi-Boot-Sticks", "Bootmedien sicher erstellen, aktualisieren und reparieren."],
  builder: ["ISO-Builder", "Geplante Änderungen nachvollziehbar in ein neues Image integrieren."],
  drivers: ["Treiber & Pakete", "Geprüfte Software und Hardwaretreiber zentral verwalten."],
  scripts: ["Skriptbibliothek", "Automatisierungen versionieren, validieren und gezielt ausführen."],
  tests: ["Virtuelle Tests", "Installationen mit QEMU prüfen, bevor ein Medium beschrieben wird."],
  logs: ["Vorgänge & Logs", "Jeder Schritt, jede Warnung und jedes Werkzeug nachvollziehbar."],
  settings: ["Einstellungen", "Darstellung, Sicherheit, Werkzeuge und Kompatibilitätsregeln."],
};

const familyMeta: Record<OsFamily, { label: string; tone: string; mark: string }> = {
  windows: { label: "Windows", tone: "blue", mark: "W" }, ubuntu: { label: "Ubuntu", tone: "orange", mark: "U" },
  debian: { label: "Debian", tone: "red", mark: "D" }, fedora: { label: "Fedora", tone: "blue", mark: "F" },
  arch: { label: "Arch", tone: "cyan", mark: "A" }, unknown: { label: "Unbekannt", tone: "gray", mark: "?" },
};

const formatBytes = (bytes: number) => `${(bytes / 1024 ** 3).toFixed(bytes > 1024 ** 3 ? 1 : 2)} GB`;
const StatusDot = ({ tone = "green" }: { tone?: string }) => <span className={`status-dot ${tone}`} aria-hidden="true" />;
const Badge = ({ children, tone = "neutral" }: { children: React.ReactNode; tone?: string }) => <span className={`badge ${tone}`}>{children}</span>;

export function BootForgeApp() {
  const [page, setPage] = useState<Page>("dashboard");
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [expert, setExpert] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [importStep, setImportStep] = useState(0);
  const [images, setImages] = useState<IsoImage[]>(exampleImages);
  const [profiles, setProfiles] = useState<InstallProfile[]>(exampleProfiles);
  const [selectedProfileId, setSelectedProfileId] = useState("dev");
  const [selectedImageId, setSelectedImageId] = useState("win11");
  const [selectedJob, setSelectedJob] = useState<JobLog>(exampleJobs[0]);
  const [toast, setToast] = useState<string | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem("bootforge-state-v1");
    if (saved) {
      window.setTimeout(() => {
        try { const parsed = JSON.parse(saved); if (parsed.profiles) setProfiles(parsed.profiles); if (parsed.theme) setTheme(parsed.theme); if (typeof parsed.expert === "boolean") setExpert(parsed.expert); } catch { /* keep safe examples */ }
      }, 0);
    }
  }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("bootforge-state-v1", JSON.stringify({ profiles, theme, expert })); }, [profiles, theme, expert]);
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(null), 2600); return () => window.clearTimeout(id); }, [toast]);

  const selectedProfile = profiles.find((item) => item.id === selectedProfileId) ?? profiles[0];
  const selectedImage = images.find((item) => item.id === selectedProfile?.imageId);
  const issues = useMemo(() => selectedProfile ? validateBuild(selectedProfile, selectedImage) : [], [selectedProfile, selectedImage]);
  const navigate = (next: Page) => { setPage(next); setMobileNav(false); };
  const updateProfile = (patch: Partial<InstallProfile>) => setProfiles((items) => items.map((item) => item.id === selectedProfile.id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item));
  const updateIdentity = (key: keyof InstallProfile["identity"], value: string) => updateProfile({ identity: { ...selectedProfile.identity, [key]: value } });
  const addMockImage = () => {
    const image: IsoImage = { ...exampleImages[1], id: `ubuntu-${Date.now()}`, name: "ubuntu-24.04.3-live-server-amd64.iso", product: "Ubuntu Server", version: "24.04.3 LTS", editions: ["Server"] };
    setImages((items) => [image, ...items]); setImportOpen(false); setImportStep(0); setSelectedImageId(image.id); setPage("isos"); setToast("ISO erfolgreich analysiert und hinzugefügt");
  };

  return (
    <div className="app-shell">
      <aside className={`sidebar ${mobileNav ? "open" : ""}`}>
        <div className="brand"><div className="brand-mark"><Sparkles size={19} /></div><div><strong>BootForge</strong><span>Studio</span></div></div>
        <button className="sidebar-close icon-button" onClick={() => setMobileNav(false)} aria-label="Navigation schließen"><X size={18} /></button>
        <nav aria-label="Hauptnavigation">
          <p className="nav-label">Arbeitsbereich</p>
          {nav.slice(0, 5).map((item) => <NavButton key={item.id} item={item} active={page === item.id} onClick={() => navigate(item.id)} />)}
          <p className="nav-label second">Ressourcen</p>
          {nav.slice(5, 9).map((item) => <NavButton key={item.id} item={item} active={page === item.id} onClick={() => navigate(item.id)} />)}
          <div className="nav-spacer" />
          {nav.slice(9).map((item) => <NavButton key={item.id} item={item} active={page === item.id} onClick={() => navigate(item.id)} />)}
        </nav>
        <div className="vault-card"><div className="vault-icon"><LockKeyhole size={17} /></div><div><strong>Secret Vault</strong><span>Entsperrt · Auto-Sperre 12 min</span></div><CheckCircle2 size={16} className="success" /></div>
      </aside>

      <main className="main-panel">
        <header className="topbar">
          <button className="mobile-menu icon-button" onClick={() => setMobileNav(true)} aria-label="Navigation öffnen"><Menu size={20} /></button>
          <div className="global-search"><Search size={17} /><input aria-label="Global suchen" placeholder="ISOs, Profile, Pakete durchsuchen …" /><kbd>⌘ K</kbd></div>
          <div className="top-actions"><div className="mode-switch" role="group" aria-label="Ansichtsmodus"><button className={!expert ? "active" : ""} onClick={() => setExpert(false)}>Assistent</button><button className={expert ? "active" : ""} onClick={() => setExpert(true)}>Experte</button></div><button className="icon-button" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label="Farbschema wechseln">{theme === "light" ? <Moon size={18} /> : <Sun size={18} />}</button><button className="avatar" aria-label="Benutzermenü">MA</button></div>
        </header>

        <div className="page-content">
          <div className="page-heading"><div><h1>{pageTitles[page][0]}</h1><p>{pageTitles[page][1]}</p></div>{page === "isos" && <button className="primary" onClick={() => setImportOpen(true)}><Plus size={17} /> ISO hinzufügen</button>}{page === "profiles" && <button className="primary" onClick={() => setToast("Profilvorlagen werden geöffnet")}><Plus size={17} /> Neues Profil</button>}</div>
          {page === "dashboard" && <Dashboard onNavigate={navigate} onImport={() => setImportOpen(true)} profiles={profiles} images={images} />}
          {page === "isos" && <IsoLibrary images={images} selected={selectedImageId} setSelected={setSelectedImageId} onImport={() => setImportOpen(true)} />}
          {page === "profiles" && selectedProfile && <Profiles profiles={profiles} selected={selectedProfile} setSelected={setSelectedProfileId} updateProfile={updateProfile} updateIdentity={updateIdentity} issues={issues} expert={expert} onNavigate={navigate} notify={setToast} />}
          {page === "multiboot" && <MultiBoot notify={setToast} />}
          {page === "builder" && selectedProfile && <Builder profile={selectedProfile} image={selectedImage} issues={issues} notify={setToast} />}
          {page === "drivers" && <Catalog />}
          {page === "scripts" && <Scripts />}
          {page === "tests" && <VirtualTests notify={setToast} />}
          {page === "logs" && <Logs selected={selectedJob} setSelected={setSelectedJob} />}
          {page === "settings" && <SettingsPage theme={theme} setTheme={setTheme} />}
        </div>
      </main>
      {mobileNav && <button className="scrim" onClick={() => setMobileNav(false)} aria-label="Navigation schließen" />}
      {importOpen && <ImportDialog step={importStep} setStep={setImportStep} close={() => { setImportOpen(false); setImportStep(0); }} finish={addMockImage} />}
      {toast && <div className="toast"><CheckCircle2 size={18} />{toast}</div>}
    </div>
  );
}

function NavButton({ item, active, onClick }: { item: NavItem; active: boolean; onClick: () => void }) { const Icon = item.icon; return <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick}><Icon size={18} strokeWidth={1.8} /><span>{item.label}</span>{item.id === "logs" && <span className="nav-count">3</span>}</button>; }

function Dashboard({ onNavigate, onImport, profiles, images }: { onNavigate: (page: Page) => void; onImport: () => void; profiles: InstallProfile[]; images: IsoImage[] }) {
  const actions = [
    { label: "ISO hinzufügen", sub: "Image analysieren", icon: FilePlus2, action: onImport, tone: "blue" },
    { label: "Multi-Boot-Stick", sub: "Medium erstellen", icon: Usb, action: () => onNavigate("multiboot"), tone: "violet" },
    { label: "Neues Profil", sub: "Vorlage auswählen", icon: Layers3, action: () => onNavigate("profiles"), tone: "green" },
    { label: "In VM testen", sub: "QEMU starten", icon: Play, action: () => onNavigate("tests"), tone: "orange" },
  ];
  return <>
    <section className="quick-grid">{actions.map(({ label, sub, icon: Icon, action, tone }) => <button className="quick-card" key={label} onClick={action}><span className={`quick-icon ${tone}`}><Icon size={21} /></span><span><strong>{label}</strong><small>{sub}</small></span><ChevronRight size={17} /></button>)}</section>
    <section className="stats-grid">
      <Stat icon={Disc3} label="ISO-Images" value={String(images.length)} sub="2 offiziell verifiziert" tone="blue" />
      <Stat icon={Layers3} label="Profile" value={String(profiles.length)} sub="Alle aktuell" tone="violet" />
      <Stat icon={Usb} label="USB-Geräte" value="1" sub="SanDisk Extreme Pro" tone="green" />
      <Stat icon={AlertTriangle} label="Aufmerksamkeit" value="2" sub="1 Build · 1 Profil" tone="orange" />
    </section>
    <div className="dashboard-grid">
      <section className="card span-2"><CardHeader title="Zuletzt verwendete Images" action="Alle anzeigen" onClick={() => onNavigate("isos")} />
        <div className="table-list">{images.slice(0, 3).map((image) => <div className="table-row" key={image.id}><OsMark family={image.family} /><div className="grow"><strong>{image.name}</strong><span>{image.product} · {image.version} · {image.architecture}</span></div><Badge tone={image.confidence === "high" ? "success" : "warning"}><StatusDot tone={image.confidence === "high" ? "green" : "orange"} />{image.confidence === "high" ? "Hohes Vertrauen" : "Prüfen"}</Badge><button className="icon-button"><MoreHorizontal size={18} /></button></div>)}</div>
      </section>
      <section className="card"><CardHeader title="Erkannte USB-Laufwerke" action="Aktualisieren" icon={RefreshCcw} /><div className="device-hero"><div className="device-icon"><Usb size={27} /></div><div><strong>SanDisk Extreme Pro</strong><span>119,2 GB · USB 3.2</span></div><Badge tone="success"><StatusDot />Bereit</Badge></div><div className="capacity"><div className="capacity-label"><span>Belegt 47,8 GB</span><span>71,4 GB frei</span></div><div className="capacity-bar"><i style={{ width: "40%" }} /></div></div><button className="secondary full" onClick={() => onNavigate("multiboot")}>Stick verwalten <ChevronRight size={16} /></button></section>
      <section className="card span-2"><CardHeader title="Aktuelle Profile" action="Alle anzeigen" onClick={() => onNavigate("profiles")} /><div className="profile-mini-grid">{profiles.slice(0, 3).map((profile) => <button key={profile.id} onClick={() => onNavigate("profiles")} className="profile-mini"><OsMark family={profile.family} /><div><strong>{profile.name}</strong><span>{profile.software.length} Pakete · {profile.scripts.postInstall.length} Skript</span></div><Badge tone={profile.id === "privacy" ? "warning" : "success"}>{profile.id === "privacy" ? "1 Warnung" : "Bereit"}</Badge></button>)}</div></section>
      <section className="card security-card"><CardHeader title="Sicherheitsstatus" /><div className="security-score"><div className="score-ring">94</div><div><strong>Gut geschützt</strong><span>Vault aktiv · Logs maskiert</span></div></div><ul className="check-list"><li><Check size={15} />Secret Vault automatisch gesperrt</li><li><Check size={15} />Systemlaufwerke geschützt</li><li className="warn"><AlertTriangle size={15} />1 Kompatibilitätsregel aktualisieren</li></ul></section>
    </div>
  </>;
}

function Stat({ icon: Icon, label, value, sub, tone }: { icon: ComponentType<{ size?: number }>; label: string; value: string; sub: string; tone: string }) { return <div className="stat-card"><span className={`stat-icon ${tone}`}><Icon size={20} /></span><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>; }
function CardHeader({ title, action, onClick, icon: Icon }: { title: string; action?: string; onClick?: () => void; icon?: ComponentType<{ size?: number }> }) { return <div className="card-header"><h2>{title}</h2>{action && <button onClick={onClick}>{Icon && <Icon size={13} />}{action}</button>}</div>; }
function OsMark({ family }: { family: OsFamily }) { const meta = familyMeta[family]; return <span className={`os-mark ${meta.tone}`}>{meta.mark}</span>; }

function IsoLibrary({ images, selected, setSelected, onImport }: { images: IsoImage[]; selected: string; setSelected: (id: string) => void; onImport: () => void }) {
  const image = images.find((item) => item.id === selected) ?? images[0];
  return <div className="split-layout"><section className="card table-card"><div className="toolbar"><div className="inline-search"><Search size={16} /><input placeholder="Images durchsuchen" /></div><button className="filter">Alle Systeme <ChevronDown size={15} /></button><button className="filter">Status <ChevronDown size={15} /></button></div><div className="iso-table"><div className="table-head"><span>Image</span><span>System</span><span>Größe</span><span>Status</span></div>{images.map((item) => <button className={`iso-row ${item.id === selected ? "selected" : ""}`} onClick={() => setSelected(item.id)} key={item.id}><span className="image-cell"><OsMark family={item.family} /><span><strong>{item.name}</strong><small>{item.sha256}</small></span></span><span>{item.product}<small>{item.version}</small></span><span>{formatBytes(item.size)}<small>{item.architecture}</small></span><span><Badge tone={item.confidence === "high" ? "success" : "warning"}>{item.confidence === "high" ? "Verifiziert" : "Prüfen"}</Badge></span></button>)}</div><button className="drop-zone" onClick={onImport}><Download size={23} /><strong>ISO hier ablegen oder auswählen</strong><span>Die Datei wird lokal analysiert und nicht hochgeladen.</span></button></section>
    <aside className="card detail-panel"><div className="detail-cover"><OsMark family={image.family} /><Badge tone="success"><ShieldCheck size={13} /> Struktur erkannt</Badge></div><h2>{image.product}</h2><p>{image.version}</p><dl className="detail-list"><div><dt>Architektur</dt><dd>{image.architecture}</dd></div><div><dt>Bootmodi</dt><dd>{image.bootModes.join(" · ").toUpperCase()}</dd></div><div><dt>Vertrauen</dt><dd><StatusDot /> Hoch</dd></div><div><dt>Prüfsumme</dt><dd className="mono">{image.sha256}</dd></div></dl><div className="detail-section"><h3>Enthaltene Editionen</h3><div className="chip-row">{image.editions.map((edition) => <Badge key={edition}>{edition}</Badge>)}</div></div><div className="detail-section"><h3>Automatisierung</h3><ul className="cap-list">{image.capabilities.map((cap) => <li key={cap}><Check size={14} />{cap}</li>)}</ul></div><button className="primary full"><Layers3 size={16} /> Profil zuweisen</button></aside>
  </div>;
}

function Profiles({ profiles, selected, setSelected, updateProfile, updateIdentity, issues, expert, onNavigate, notify }: { profiles: InstallProfile[]; selected: InstallProfile; setSelected: (id: string) => void; updateProfile: (patch: Partial<InstallProfile>) => void; updateIdentity: (key: keyof InstallProfile["identity"], value: string) => void; issues: ValidationIssue[]; expert: boolean; onNavigate: (page: Page) => void; notify: (message: string) => void }) {
  const [tab, setTab] = useState("basic"); const adapter = adapters.find((item) => item.supports(selected)); const artifacts = adapter?.generate(selected) ?? [];
  return <div className="profile-layout"><aside className="card profile-list"><div className="inline-search"><Search size={16} /><input placeholder="Profile suchen" /></div>{profiles.map((profile) => <button className={`profile-list-item ${profile.id === selected.id ? "active" : ""}`} onClick={() => setSelected(profile.id)} key={profile.id}><OsMark family={profile.family} /><span><strong>{profile.name}</strong><small>{profile.description}</small></span><ChevronRight size={16} /></button>)}</aside>
    <section className="card editor-card"><div className="editor-head"><div><div className="eyebrow"><Badge tone="info">{selected.outputMode === "dynamic" ? "Dynamische Konfiguration" : selected.outputMode}</Badge><span>Gespeichert</span></div><input className="title-input" value={selected.name} onChange={(event) => updateProfile({ name: event.target.value })} aria-label="Profilname" /><p>{selected.description}</p></div><button className="icon-button"><MoreHorizontal size={18} /></button></div>
      <div className="editor-progress"><span><i className="done"><Check size={13} /></i>Grundkonfiguration</span><b /><span><i className="done"><Check size={13} /></i>Anpassungen</span><b /><span><i className={issues.some((item) => item.level === "error") ? "error" : "warn"}>{issues.length}</i>Validierung</span></div>
      <div className="editor-body"><nav className="section-nav">{profileSections.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? "active" : ""}><Icon size={16} />{label}{id === "compat" && issues.length > 1 && <Badge tone="warning">{issues.filter((item) => item.level === "warning").length}</Badge>}</button>)}</nav>
        <div className="form-area">{tab === "basic" && <><SectionTitle title="Grundkonfiguration" sub="Identität, Sprache und Installationsmodus" /><div className="form-grid"><Field label="Computername"><input value={selected.identity.hostname} onChange={(e) => updateIdentity("hostname", e.target.value)} /></Field><Field label="Ausgabemodus"><select value={selected.outputMode} onChange={(e) => updateProfile({ outputMode: e.target.value as InstallProfile["outputMode"] })}><option value="dynamic">Dynamisch (empfohlen)</option><option value="multiboot">Multi-Boot</option><option value="custom-iso">Angepasste ISO</option></select></Field><Field label="Sprache & Region"><select value={selected.identity.locale} onChange={(e) => updateIdentity("locale", e.target.value)}><option>de-DE</option><option>en-US</option><option>de_DE.UTF-8</option></select></Field><Field label="Tastatur"><select value={selected.identity.keyboard} onChange={(e) => updateIdentity("keyboard", e.target.value)}><option>de-DE</option><option>de</option><option>en-US</option></select></Field><Field label="Zeitzone"><input value={selected.identity.timezone} onChange={(e) => updateIdentity("timezone", e.target.value)} /></Field><Field label="Netzwerk während Setup"><select value={selected.network.offline ? "offline" : "online"} onChange={(e) => updateProfile({ network: { ...selected.network, offline: e.target.value === "offline" } })}><option value="online">Online zulassen</option><option value="offline">Offline installieren</option></select></Field></div><InfoCallout title="Original-ISO bleibt unverändert">Die Konfiguration wird beim Booten bereitgestellt. Das spart Speicher und erleichtert Updates.</InfoCallout></>}
        {tab === "users" && <><SectionTitle title="Benutzerkonten" sub="Keine Kennwörter werden im Profil gespeichert" />{selected.users.map((user, index) => <div className="user-card" key={index}><div className="user-avatar"><Users size={20} /></div><div className="form-grid compact"><Field label="Benutzername"><input value={user.username} readOnly /></Field><Field label="Rolle"><select defaultValue={user.role}><option value="administrator">Administrator</option><option value="standard">Standardbenutzer</option></select></Field><Field label="Kontotyp"><select defaultValue={user.accountType}><option value="local">Lokales Konto</option><option value="microsoft">Microsoft-Konto</option><option value="domain">Domänenkonto</option></select></Field><Field label="Kennwort"><select defaultValue={user.passwordMode}><option value="prompt_at_install">Bei Installation abfragen</option><option value="temporary">Temporär erzeugen</option><option value="vault">Aus Secret Vault</option><option value="none">Ohne Kennwort (unsicher)</option></select></Field></div></div>)}<button className="secondary"><Plus size={16} /> Benutzer hinzufügen</button></>}
        {tab === "storage" && <><SectionTitle title="Festplatte" sub="Destruktive Schritte werden vor dem Build gesondert bestätigt" /><div className="choice-grid"><button className={selected.storage.mode === "guided" ? "selected" : ""} onClick={() => updateProfile({ storage: { ...selected.storage, mode: "guided" } })}><Sparkles size={20} /><strong>Automatisch</strong><span>Systempartitionen passend anlegen</span></button><button className={selected.storage.mode === "manual" ? "selected" : ""} onClick={() => updateProfile({ storage: { ...selected.storage, mode: "manual" } })}><HardDrive size={20} /><strong>Manuell</strong><span>Installer zeigt Partitionsdialog</span></button></div><div className="form-grid"><Field label="Partitionstabelle"><select defaultValue={selected.storage.partitionTable}><option>gpt</option><option>mbr</option></select></Field><Field label="Verschlüsselung"><select defaultValue={selected.storage.encryption}><option>none</option><option>bitlocker</option><option>luks</option></select></Field></div><WarningCallout title="Speicheraktion prüfen">Automatische Partitionierung kann alle Daten auf dem Ziel löschen. Der Ziel-Datenträger wird erst während der Installation ausgewählt.</WarningCallout></>}
        {tab === "network" && <><SectionTitle title="Netzwerk" sub="Verbindung und Setup-Abhängigkeiten" /><div className="form-grid"><Field label="Konfiguration"><select defaultValue={selected.network.mode}><option value="dhcp">DHCP</option><option value="static">Statische Adresse</option></select></Field><Toggle label="Offline-Installation" checked={selected.network.offline} onChange={(checked) => updateProfile({ network: { ...selected.network, offline: checked } })} /></div></>}
        {tab === "software" && <><SectionTitle title="Software" sub={`${selected.software.length} Pakete in definierter Reihenfolge`} /><div className="package-list">{selected.software.map((item, i) => <div key={item.id}><span className="order">{i + 1}</span><Package size={18} /><span><strong>{item.id}</strong><small>{item.source} · Neueste stabile Version</small></span><Badge tone="success">Geprüft</Badge><button className="icon-button"><MoreHorizontal size={17} /></button></div>)}</div><button className="secondary"><Plus size={16} /> Paket hinzufügen</button></>}
        {tab === "compat" && <><SectionTitle title="Windows-Kompatibilität" sub="Diese Optionen können Support, Updates und Stabilität beeinträchtigen" /><WarningCallout title="Nicht unterstützte Konfiguration">Aktiviere Prüfungsumgehungen nur nach einem Hardware-Kompatibilitätsbericht.</WarningCallout><div className="toggle-list"><Toggle label="TPM-2.0-Prüfung überspringen" checked={selected.compatibility.bypassTpm} onChange={(checked) => updateProfile({ compatibility: { ...selected.compatibility, bypassTpm: checked } })} /><Toggle label="Secure-Boot-Prüfung überspringen" checked={selected.compatibility.bypassSecureBoot} onChange={(checked) => updateProfile({ compatibility: { ...selected.compatibility, bypassSecureBoot: checked } })} /><Toggle label="RAM-Prüfung überspringen" checked={selected.compatibility.bypassRam} onChange={(checked) => updateProfile({ compatibility: { ...selected.compatibility, bypassRam: checked } })} /></div></>}
        {tab === "files" && <><SectionTitle title="Erzeugte Dateien" sub={expert ? "Expertenansicht · Änderungen werden aus dem Profil neu generiert" : "Vorschau der Adapter-Ausgabe"} /><div className="file-tabs">{artifacts.map((file) => <Badge key={file.path} tone="info">{file.path}</Badge>)}</div><pre className="code-preview">{artifacts[0]?.content ?? "Für dieses Betriebssystem ist noch kein Adapter implementiert."}</pre><InfoCallout title="Schreibschutz für manuelle Änderungen">Im MVP ist die Textansicht schreibgeschützt. So werden manuelle Änderungen nicht unbemerkt überschrieben.</InfoCallout></>}</div>
      </div>
      <div className="editor-footer"><div className="validation-summary"><span className="success"><CheckCircle2 size={16} />0 Fehler</span><span className="warning"><AlertTriangle size={16} />{issues.filter((item) => item.level === "warning").length} Warnungen</span></div><div><button className="secondary" onClick={() => onNavigate("tests")}><Play size={16} /> In VM testen</button><button className="primary" onClick={() => { onNavigate("builder"); notify("Build-Plan aus aktuellem Profil erstellt"); }}><Archive size={16} /> Ausgabe erstellen</button></div></div>
    </section>
  </div>;
}

function SectionTitle({ title, sub }: { title: string; sub: string }) { return <div className="section-title"><h3>{title}</h3><p>{sub}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><i /></label>; }
function InfoCallout({ title, children }: { title: string; children: React.ReactNode }) { return <div className="callout info"><Info size={18} /><div><strong>{title}</strong><p>{children}</p></div></div>; }
function WarningCallout({ title, children }: { title: string; children: React.ReactNode }) { return <div className="callout warning"><AlertTriangle size={18} /><div><strong>{title}</strong><p>{children}</p></div></div>; }

function MultiBoot({ notify }: { notify: (message: string) => void }) {
  const device = exampleDevices[0]; const safety = evaluateUsbTarget(device); const [selected, setSelected] = useState(true);
  return <div className="multiboot-grid"><section className="card"><CardHeader title="Zielgerät" action="Neu erkennen" icon={RefreshCcw} /><div className="safe-device"><span className="device-icon"><Usb size={28} /></span><div><strong>{device.vendor} {device.model}</strong><span>{formatBytes(device.size)} · Seriennummer {device.serial}</span></div><Badge tone="success"><ShieldCheck size={13} /> Sicher erkannt</Badge></div><div className="capacity"><div className="capacity-bar"><i style={{ width: "40%" }} /></div><div className="capacity-label"><span>47,8 GB belegt</span><span>71,4 GB frei</span></div></div><InfoCallout title="Systemlaufwerkschutz aktiv">Interne Laufwerke werden ausgeblendet und können nicht als Ziel verwendet werden.</InfoCallout></section>
    <section className="card"><CardHeader title="Boot-Backend" /><div className="backend-card"><div className="backend-logo">V</div><div><strong>Ventoy (extern)</strong><span>Backend erkannt · Version 1.1.05</span></div><Badge tone="mock">Mock-Adapter</Badge></div><dl className="detail-list compact"><div><dt>UEFI</dt><dd><Check size={15} /> Unterstützt</dd></div><div><dt>Legacy BIOS</dt><dd><Check size={15} /> Unterstützt</dd></div><div><dt>Secure Boot</dt><dd>Bereit zur Registrierung</dd></div></dl><button className="secondary full">Backend wechseln <ChevronRight size={16} /></button></section>
    <section className="card span-2"><CardHeader title="Bootmenü" action="Menü gestalten" /><div className="boot-layout"><div className="boot-tree"><div><ChevronDown size={15} /><FolderLabel label="Windows" /></div><button className={selected ? "active" : ""} onClick={() => setSelected(true)}><span /><OsMark family="windows" /><div><strong>Windows 11</strong><small>3 Profile · Standard: Development</small></div></button><div><ChevronDown size={15} /><FolderLabel label="Linux" /></div><button onClick={() => setSelected(false)}><span /><OsMark family="ubuntu" /><div><strong>Ubuntu 24.04 LTS</strong><small>2 Profile · 4 GB Persistenz</small></div></button><div><ChevronRight size={15} /><FolderLabel label="Werkzeuge" /></div></div><div className="boot-config"><h3>Windows 11</h3><p>Win11_25H2_German_x64.iso</p><div className="assigned-profile"><Layers3 size={18} /><div><strong>Windows 11 Development</strong><span>Standardprofil · Dynamisch</span></div><Badge tone="success">Bereit</Badge></div><button className="secondary full"><Plus size={16} /> Weiteres Profil zuweisen</button></div></div><div className="build-bar"><div><ShieldCheck size={19} /><span><strong>{safety.allowed ? "Sicherheitsprüfung bestanden" : "Ziel gesperrt"}</strong><small>2 Images · 5 Profile · 18,4 GB</small></span></div><button className="danger" onClick={() => notify(`Bestätigung erforderlich: ${safety.confirmation}`)}><Usb size={16} /> Stick aktualisieren</button></div></section></div>;
}
function FolderLabel({ label }: { label: string }) { return <><Library size={16} /><strong>{label}</strong></>; }

function Builder({ profile, image, issues, notify }: { profile: InstallProfile; image?: IsoImage; issues: ValidationIssue[]; notify: (message: string) => void }) {
  const [accepted, setAccepted] = useState(false); const errors = issues.filter((i) => i.level === "error"); const warnings = issues.filter((i) => i.level === "warning"); const ready = canStartBuild(issues) && (warnings.length === 0 || accepted);
  return <div className="builder-layout"><section className="card"><div className="build-source"><OsMark family={profile.family} /><div><span>Quelle</span><strong>{image?.name ?? "ISO nicht verfügbar"}</strong><small>{image?.sha256}</small></div><ChevronRight /><div><span>Profil</span><strong>{profile.name}</strong><small>Schema v{profile.schemaVersion} · {profile.outputMode}</small></div></div></section><section className="card"><CardHeader title="Build-Plan" /><div className="timeline">{[["01", "Original-ISO prüfen", "Nur lesen · SHA-256 verifizieren", "done"], ["02", "Antwortdateien erzeugen", profile.family === "windows" ? "autounattend.xml · SetupComplete.ps1" : "user-data · meta-data", "ready"], ["03", "Pakete & Skripte bereitstellen", `${profile.software.length} Pakete · ${profile.scripts.postInstall.length} Skript`, "ready"], ["04", "Konfigurationsstruktur exportieren", "Atomarer Schreibvorgang · Original bleibt unverändert", "ready"], ["05", "Prüfsumme & Bericht", "SHA-256 · JSON-Protokoll", "ready"]].map(([n, title, sub, state]) => <div key={n}><span className={state}>{state === "done" ? <Check size={15} /> : n}</span><div><strong>{title}</strong><small>{sub}</small></div><Badge tone={state === "done" ? "success" : "neutral"}>{state === "done" ? "Geprüft" : "Geplant"}</Badge></div>)}</div></section><aside className="card"><CardHeader title="Preflight" /><ValidationList issues={issues} /><label className="confirm-check"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} /><span>Ich habe die {warnings.length} Warnungen geprüft.</span></label><button className="primary full" disabled={!ready} onClick={() => notify("Build-Job JOB-240802-018 wurde gestartet")}><Play size={16} /> Build starten</button>{errors.length > 0 && <p className="blocked-note"><XCircle size={14} /> Fehler müssen zuerst behoben werden.</p>}</aside></div>;
}
function ValidationList({ issues }: { issues: ValidationIssue[] }) { return <div className="validation-list">{issues.map((issue) => <div key={issue.id} className={issue.level}>{issue.level === "error" ? <XCircle size={18} /> : issue.level === "warning" ? <AlertTriangle size={18} /> : <Info size={18} />}<div><strong>{issue.title}</strong><span>{issue.message}</span></div></div>)}</div>; }

function Catalog() { return <div className="catalog-layout"><section className="card"><div className="toolbar"><div className="inline-search"><Search size={16} /><input placeholder="Pakete und Treiber suchen" /></div><button className="primary"><Plus size={16} /> Importieren</button></div><div className="catalog-tabs"><button className="active">Software <Badge>12</Badge></button><button>Treiber <Badge>8</Badge></button><button>Gruppen <Badge>4</Badge></button></div><div className="package-table">{[["Git", "Git.Git", "Winget", "2.49.0"], ["Visual Studio Code", "Microsoft.VisualStudioCode", "Winget", "1.104"], ["Mozilla Firefox", "Mozilla.Firefox", "Winget", "141.0"], ["Intel VMD Storage", "PCI\\VEN_8086&DEV_467F", "INF", "20.2.1"]].map(([name, id, source, version]) => <div key={id}><span className="package-icon"><Package size={18} /></span><div><strong>{name}</strong><small>{id}</small></div><Badge>{source}</Badge><span>{version}</span><Badge tone="success">Validiert</Badge><button className="icon-button"><MoreHorizontal size={17} /></button></div>)}</div></section><aside className="card"><CardHeader title="Katalogstatus" /><div className="catalog-score"><ShieldCheck size={30} /><strong>20 von 20 geprüft</strong><span>Metadaten zuletzt heute, 08:00 aktualisiert</span></div><ul className="detail-list plain"><li><span>Offline verfügbar</span><strong>7 Pakete</strong></li><li><span>Versionssperren</span><strong>3</strong></li><li><span>Signierte Treiber</span><strong>8 / 8</strong></li><li><span>Offene Warnungen</span><strong className="warning">1</strong></li></ul></aside></div>; }

function Scripts() { const [script, setScript] = useState("windows"); return <div className="scripts-layout"><aside className="card script-list"><div className="inline-search"><Search size={16} /><input placeholder="Skripte suchen" /></div>{[["windows", "setup-development.ps1", "PowerShell"], ["linux", "harden-host.sh", "Shell"], ["registry", "privacy-baseline.reg", "Registry"]].map(([id, name, type]) => <button className={script === id ? "active" : ""} onClick={() => setScript(id)} key={id}><span className="file-icon"><FileCode2 size={18} /></span><span><strong>{name}</strong><small>{type} · v3</small></span><Badge tone="success">Geprüft</Badge></button>)}</aside><section className="card code-card"><div className="code-head"><div><strong>{script === "linux" ? "harden-host.sh" : script === "registry" ? "privacy-baseline.reg" : "setup-development.ps1"}</strong><span>Schreibgeschützte Vorschau · SHA-256 geprüft</span></div><button className="secondary"><Play size={15} /> Testlauf</button></div><pre>{script === "linux" ? `#!/usr/bin/env bash\nset -euo pipefail\n\nhostnamectl set-hostname \"\${HOSTNAME}\"\nsystemctl enable --now ufw\nufw default deny incoming\nufw allow OpenSSH\n\necho \"BootForge health check: OK\"` : script === "registry" ? `Windows Registry Editor Version 5.00\n\n[HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection]\n\"AllowTelemetry\"=dword:00000001` : `#requires -version 7.0\n$ErrorActionPreference = 'Stop'\n\nWrite-Host \"Configuring $env:COMPUTERNAME\"\nwinget install --id Git.Git --silent\nwinget install --id Microsoft.VisualStudioCode --silent\n\nWrite-Host \"Health check: OK\"`}</pre><div className="variable-bar"><span>Variablen</span>{["HOSTNAME", "USERNAME", "PROFILE_NAME"].map((v) => <Badge key={v} tone="info">{`\${${v}}`}</Badge>)}</div></section></div>; }

function VirtualTests({ notify }: { notify: (message: string) => void }) { return <div className="tests-grid"><section className="card vm-card"><div className="vm-preview"><div className="vm-screen"><Command size={42} /><span>BootForge QEMU Console</span><small>Bereit für Teststart</small></div><div className="vm-controls"><button><Play size={15} /></button><button><RefreshCcw size={15} /></button><span>00:00:00</span></div></div></section><aside className="card"><CardHeader title="Testkonfiguration" /><div className="form-grid one"><Field label="Profil"><select><option>Windows 11 Development</option><option>Ubuntu Docker Host</option></select></Field><Field label="Firmware"><select><option>UEFI (OVMF)</option><option>Legacy BIOS</option></select></Field><Field label="Arbeitsspeicher"><select><option>8 GB</option><option>4 GB</option><option>16 GB</option></select></Field><Field label="CPU"><select><option>4 Kerne</option><option>2 Kerne</option><option>8 Kerne</option></select></Field></div><div className="toggle-list compact"><Toggle label="TPM 2.0 simulieren" checked={true} onChange={() => {}} /><Toggle label="Netzwerk deaktivieren" checked={false} onChange={() => {}} /><Toggle label="Snapshot nach Installation" checked={true} onChange={() => {}} /></div><Badge tone="mock">Mock-Adapter · QEMU-Aufruf wird vorbereitet</Badge><button className="primary full" onClick={() => notify("QEMU-Testjob wurde vorbereitet")}><Play size={16} /> Test starten</button></aside><section className="card span-2"><CardHeader title="Letzter Testbericht" action="Bericht öffnen" /><div className="test-results">{[["ISO bootfähig", "Erfolgreich", "success"], ["Antwortdatei erkannt", "Erfolgreich", "success"], ["Partitionierung", "Erfolgreich", "success"], ["Benutzer angelegt", "Erfolgreich", "success"], ["Softwareinstallation", "7 von 8", "warning"]].map(([label, result, tone]) => <div key={label}>{tone === "success" ? <CheckCircle2 className="success" size={18} /> : <AlertTriangle className="warning" size={18} />}<span>{label}</span><Badge tone={tone}>{result}</Badge></div>)}</div></section></div>; }

function Logs({ selected, setSelected }: { selected: JobLog; setSelected: (job: JobLog) => void }) { return <div className="logs-layout"><section className="card job-list"><div className="toolbar"><div className="inline-search"><Search size={16} /><input placeholder="Job-ID oder Vorgang suchen" /></div><button className="filter">Alle Status <ChevronDown size={15} /></button></div>{exampleJobs.map((job) => <button className={selected.id === job.id ? "active" : ""} onClick={() => setSelected(job)} key={job.id}><span className={`job-status ${job.status}`}>{job.status === "success" ? <Check size={17} /> : job.status === "failed" ? <X size={17} /> : <AlertTriangle size={17} />}</span><div><strong>{job.summary}</strong><span>{job.id} · {job.startedAt}</span></div><Badge tone={job.status === "success" ? "success" : job.status === "failed" ? "danger" : "warning"}>{job.status === "success" ? "Erfolgreich" : job.status === "failed" ? "Fehlgeschlagen" : "Warnung"}</Badge></button>)}</section><aside className="card log-detail"><div className="log-heading"><div><span>{selected.id}</span><h2>{selected.summary}</h2></div><button className="secondary"><Download size={15} /> Exportieren</button></div><div className="progress-line"><i style={{ width: `${selected.progress}%` }} /></div><dl className="detail-list compact"><div><dt>Status</dt><dd><Badge tone={selected.status === "success" ? "success" : selected.status === "failed" ? "danger" : "warning"}>{selected.status}</Badge></dd></div><div><dt>Beginn</dt><dd>{selected.startedAt}</dd></div><div><dt>Ende</dt><dd>{selected.endedAt ?? "–"}</dd></div><div><dt>Fortschritt</dt><dd>{selected.progress}%</dd></div></dl><div className="log-stream">{selected.steps.map((step, index) => <div key={index} className={step.level}><code>{step.at}</code>{step.level === "error" ? <XCircle size={15} /> : step.level === "warning" ? <AlertTriangle size={15} /> : <Info size={15} />}<span>{step.message}</span></div>)}</div><InfoCallout title="Secrets werden automatisch maskiert">Kennwörter, Tokens und Vault-Werte erscheinen weder hier noch im Export.</InfoCallout></aside></div>; }

function SettingsPage({ theme, setTheme }: { theme: "light" | "dark"; setTheme: (value: "light" | "dark") => void }) { return <div className="settings-layout"><aside className="card settings-nav">{settingsSections.map(([id, label, Icon], i) => <button className={i === 0 ? "active" : ""} key={id}><Icon size={17} />{label}<ChevronRight size={15} /></button>)}</aside><section className="card settings-form"><SectionTitle title="Allgemein" sub="Darstellung und Arbeitsweise von BootForge Studio" /><div className="setting-block"><h3>Darstellung</h3><div className="theme-choice"><button className={theme === "light" ? "active" : ""} onClick={() => setTheme("light")}><Sun size={23} /><strong>Hell</strong></button><button className={theme === "dark" ? "active" : ""} onClick={() => setTheme("dark")}><Moon size={23} /><strong>Dunkel</strong></button></div></div><div className="setting-block"><h3>Verhalten</h3><div className="toggle-list"><Toggle label="Dynamische Konfiguration als Standard" checked={true} onChange={() => {}} /><Toggle label="Expertenoptionen standardmäßig ausblenden" checked={true} onChange={() => {}} /><Toggle label="Vor destruktiven Aktionen Bestätigungstext verlangen" checked={true} onChange={() => {}} /><Toggle label="Anonyme Update-Prüfung" checked={true} onChange={() => {}} /></div></div><div className="setting-block"><h3>Lokale Speicherung</h3><p className="muted">Profile und UI-Einstellungen werden lokal gespeichert. Secrets liegen getrennt im verschlüsselten Vault.</p><button className="secondary"><Archive size={16} /> Profile exportieren</button></div></section></div>; }

function ImportDialog({ step, setStep, close, finish }: { step: number; setStep: (n: number) => void; close: () => void; finish: () => void }) {
  const stages = ["Datei wählen", "Analysieren", "Ergebnis"];
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="modal"><div className="modal-head"><div><span className="eyebrow">ISO-Import</span><h2 id="import-title">Neues Image hinzufügen</h2></div><button className="icon-button" onClick={close} aria-label="Schließen"><X size={19} /></button></div><div className="stepper">{stages.map((label, index) => <div className={index <= step ? "active" : ""} key={label}><span>{index < step ? <Check size={14} /> : index + 1}</span><strong>{label}</strong>{index < stages.length - 1 && <i />}</div>)}</div>
    <div className="modal-body">{step === 0 && <div className="file-picker"><span className="picker-icon"><Disc3 size={30} /></span><h3>ISO-Datei auswählen</h3><p>Die Datei wird ausschließlich lokal gelesen. Originaldaten werden nicht verändert.</p><button className="primary" onClick={() => setStep(1)}><FilePlus2 size={17} /> ubuntu-24.04.3-live-server-amd64.iso</button><small>5,9 GB · ISO 9660 / UDF</small></div>}{step === 1 && <div className="analysis-progress"><div className="scan-orbit"><Disc3 size={34} /></div><h3>Image wird analysiert</h3><p>Prüfsumme, Bootstruktur und Betriebssystemmerkmale werden geprüft.</p><div className="analysis-steps"><div><CheckCircle2 size={17} /><span>SHA-256 berechnet</span><code>d7fe3b…92ab</code></div><div><CheckCircle2 size={17} /><span>ISO-Struktur gelesen</span><code>ISO 9660</code></div><div><CheckCircle2 size={17} /><span>UEFI und BIOS erkannt</span><code>Hybrid</code></div><div className="active"><RefreshCcw size={17} /><span>Metadaten auswerten</span><code>casper/</code></div></div><button className="primary" onClick={() => setStep(2)}>Analyse abschließen</button></div>}{step === 2 && <div className="result-view"><div className="result-title"><OsMark family="ubuntu" /><div><Badge tone="success"><ShieldCheck size={13} /> Hohes Vertrauen</Badge><h3>Ubuntu Server</h3><p>24.04.3 LTS · amd64</p></div></div><dl className="result-grid"><div><dt>Bootmodi</dt><dd>UEFI · Legacy BIOS</dd></div><div><dt>Image-Typ</dt><dd>Server · Live Installer</dd></div><div><dt>Automatisierung</dt><dd>Autoinstall · Cloud-init</dd></div><div><dt>Prüfsumme</dt><dd className="mono">d7fe3b63…92ab</dd></div></dl><InfoCallout title="Passende Vorlage verfügbar">„Ubuntu Server“ kann nach dem Import als Ausgangsprofil verwendet werden.</InfoCallout></div>}</div><div className="modal-footer"><button className="secondary" onClick={step === 0 ? close : () => setStep(step - 1)}>{step === 0 ? "Abbrechen" : "Zurück"}</button><button className="primary" disabled={step < 2} onClick={finish}>Image hinzufügen <ChevronRight size={16} /></button></div></div></div>;
}
